[build]
builder = "NIXPACKS"

[deploy]
startCommand = "gunicorn app:app --preload"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Persistent volume for historical data
[[deploy.volumes]]
mountPath = "/app/data"
